services:
  db:
    image: postgres:17.2-alpine3.20
    environment:
      POSTGRES_DB: spectro
    env_file:
      - .env.development
    restart: always
    ports:
      - 5555:5432
    profiles:
      - dev
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready --username=postgres --dbname=spectro
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  postgres:
