services:
  db:
    image: postgres:17.5-alpine3.22
    env_file:
      - .env.development
    user: postgres
    restart: always
    ports:
      - 5432:5432
    profiles:
      - dev
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  postgres:
