app = 'spectro'
primary_region = 'hkg'

[[vm]]
size = 'shared-cpu-1x'

[deploy]
strategy = 'bluegreen'

[http_service]
processes = ['app']
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

[[http_service.checks]]
method = "GET"
path = "/health"
grace_period = "3s"
interval = "6s"
timeout = "12s"
