app = 'spectro'
primary_region = 'hkg'

[[vm]]
size = 'shared-cpu-1x'

[deploy]
strategy = 'bluegreen'

[http_service]
processes = ['app']
internal_port = 3000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 1

[[http_service.checks]]
method = "GET"
path = "/health"
grace_period = "2s"
interval = "1m"
timeout = "4s"
