allowBuilds:
  esbuild: true
  protobufjs: false

catalogPrune: true

engineStrict: true

minimumReleaseAgeStrict: true

overrides:
  '@inngest/ai@0.1.7>@types/node': '-'
  '@inngest/ai@0.1.7>typescript': '-'
  'inngest@4.20.0>@opentelemetry/auto-instrumentations-node': '-'
  'inngest@4.20.0>@opentelemetry/context-async-hooks': '-'
  'inngest@4.20.0>@opentelemetry/instrumentation': '-'
  'inngest@4.20.0>@traceloop/instrumentation-anthropic': '-'

tasks:
  ci:
    dependsOn:
      - fmt
      - lint
      - test:run
  lint:
    dependsOn:
      - lint:eslint
      - lint:svelte

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - ts-api-utils@2.3.0
