engineStrict: true

minimumReleaseAge: 1440 # 1 Day

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs
  - sharp
  - workerd

patchedDependencies:
  '@neondatabase/serverless': patches/@neondatabase__serverless.patch

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - undici-types@6.21.0
