engineStrict: true

minimumReleaseAge: 1440 # 1 Day

onlyBuiltDependencies:
  - esbuild
  - protobufjs

patchedDependencies:
  '@neondatabase/serverless': patches/@neondatabase__serverless.patch

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@types/node@22.19.3'
  - chokidar@4.0.3
