allowBuilds:
  esbuild: true
  protobufjs: false

cleanupUnusedCatalogs: true

engineStrict: true

minimumReleaseAgeStrict: true

patchedDependencies:
  '@inngest/ai': patches/@inngest__ai.patch

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - ts-api-utils@2.3.0
  - undici-types@6.21.0
